name: Deploy Firebase Rules DEV

on:
  push:
    branches: [dev]
    paths:
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'storage.rules'
      - 'test/**'

jobs:
  deploy_rules:
    runs-on: ubuntu-latest

    environment:
      name: dev

    defaults:
      run:
        working-directory: test
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: test/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm --filter test i

      - name: Run Tests
        run: pnpm run test:dev

      - name: Deploy
        run: firebase deploy --only storage,firestore --project dev
