name: Deploy Firebase Rules DEV

on:
  push:
    branches: [dev]
    paths:
      - 'firestore.indexes.json'
      - 'firestore.rules'
      - 'storage.rules'
      - 'test/**'

jobs:
  deploy_rules:
    runs-on: ubuntu-latest

    environment:
      name: dev

    defaults:
      run:
        working-directory: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
          cache-dependency-path: test/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm --filter test i

      - name: Run Tests
        run: pnpm run test:dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Deploy Rules
        uses: w9jds/firebase-action@v11.5.0
        with:
          args: deploy --only storage,firestore --project dev
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
